// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Decrypt(arg1:string,arg2:string):Promise<main.OperationResult>;

export function Encrypt(arg1:string,arg2:string):Promise<main.OperationResult>;

export function SaveToFile(arg1:string,arg2:string):Promise<main.OperationResult>;

export function SelectAndReadFile():Promise<main.FileReadResult>;

export function ValidateInput(arg1:string):Promise<main.InputValidationResult>;

export function ValidateKey(arg1:string):Promise<main.KeyValidationResult>;
