// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrypt(arg1:string,arg2:string):Promise<void>;

export function Encrypt(arg1:string,arg2:string):Promise<void>;

export function GetKeyInfo():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function SaveFileDialog():Promise<string>;

export function SetKey(arg1:string):Promise<void>;
