// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertToBinaryKey(arg1) {
  return window['go']['main']['App']['ConvertToBinaryKey'](arg1);
}

export function DecryptFile(arg1, arg2) {
  return window['go']['main']['App']['DecryptFile'](arg1, arg2);
}

export function DecryptText(arg1, arg2) {
  return window['go']['main']['App']['DecryptText'](arg1, arg2);
}

export function EncryptFile(arg1, arg2) {
  return window['go']['main']['App']['EncryptFile'](arg1, arg2);
}

export function EncryptText(arg1, arg2) {
  return window['go']['main']['App']['EncryptText'](arg1, arg2);
}

export function SelectInputFile() {
  return window['go']['main']['App']['SelectInputFile']();
}

export function SelectOutputFile(arg1) {
  return window['go']['main']['App']['SelectOutputFile'](arg1);
}
