// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertToBinaryKey(arg1:string):Promise<main.KeyValidationResult>;

export function DecryptFile(arg1:string,arg2:string):Promise<main.OperationResult>;

export function DecryptText(arg1:string,arg2:string):Promise<main.OperationResult>;

export function EncryptFile(arg1:string,arg2:string):Promise<main.OperationResult>;

export function EncryptText(arg1:string,arg2:string):Promise<main.OperationResult>;

export function SelectInputFile():Promise<string>;

export function SelectOutputFile(arg1:string):Promise<string>;
