// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrypt(arg1, arg2) {
  return window['go']['main']['App']['Decrypt'](arg1, arg2);
}

export function Encrypt(arg1, arg2) {
  return window['go']['main']['App']['Encrypt'](arg1, arg2);
}

export function SaveToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveToFile'](arg1, arg2);
}

export function SelectAndReadFile() {
  return window['go']['main']['App']['SelectAndReadFile']();
}

export function ValidateInput(arg1) {
  return window['go']['main']['App']['ValidateInput'](arg1);
}

export function ValidateKey(arg1) {
  return window['go']['main']['App']['ValidateKey'](arg1);
}
